/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'voiceSpeed' : bigint,
  'reduceMotion' : boolean,
  'highContrastMode' : boolean,
  'dyslexicFont' : boolean,
  'colorBlindnessMode' : boolean,
  'largeTapTargets' : boolean,
  'soundEnabled' : boolean,
  'textToSpeechEnabled' : boolean,
  'autoAdvance' : boolean,
}
export interface ChildProfile {
  'id' : bigint,
  'arcadeHighScores' : Array<[string, bigint]>,
  'name' : string,
  'progress' : Array<UnitProgress>,
  'dailyStreak' : DailyStreak,
  'avatar' : string,
}
export interface DailyStreak { 'lastActivity' : Time, 'currentStreak' : bigint }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface LessonProgress {
  'lessonIndex' : bigint,
  'attempts' : bigint,
  'stars' : bigint,
  'hintsUsed' : bigint,
}
export type PipelineStage = { 'nlpParser' : null } |
  { 'encoder' : null } |
  { 'scriptGenerator' : null };
export type PipelineState = { 'idle' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export interface PipelineStatus {
  'nlpParser' : PipelineState,
  'encoder' : PipelineState,
  'scriptGenerator' : PipelineState,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface ServerStatus { 'online' : boolean }
export type Time = bigint;
export interface UnitProgress {
  'lessons' : Array<LessonProgress>,
  'unitIndex' : bigint,
}
export interface UserData {
  'activeProfileId' : [] | [bigint],
  'settings' : AppSettings,
  'parentPinHash' : [] | [string],
  'profiles' : Array<ChildProfile>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__onboardingFlags' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, boolean]>
  >,
  '__pipelineStates' : ActorMethod<[], any>,
  '__userData' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, UserData]>
  >,
  '__userProfiles' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, UserProfile]>
  >,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProfile' : ActorMethod<[bigint], undefined>,
  'getActiveProfile' : ActorMethod<[], [] | [ChildProfile]>,
  'getArcadeHighScore' : ActorMethod<[bigint, string], [] | [bigint]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHasSeenOnboarding' : ActorMethod<[], boolean>,
  'getPipelineStatus' : ActorMethod<[string], PipelineStatus>,
  'getProfiles' : ActorMethod<[], Array<ChildProfile>>,
  'getServerStatus' : ActorMethod<[], ServerStatus>,
  'getSettings' : ActorMethod<[], AppSettings>,
  'getStreak' : ActorMethod<[bigint], DailyStreak>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasParentPin' : ActorMethod<[], boolean>,
  'initializeUserData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'runPipeline' : ActorMethod<[string], PipelineStatus>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProfile' : ActorMethod<[ChildProfile], undefined>,
  'sendParentWeeklySummaryEmail' : ActorMethod<[string, string], undefined>,
  'setHasSeenOnboarding' : ActorMethod<[], undefined>,
  'setParentPin' : ActorMethod<[string], undefined>,
  'switchActiveProfile' : ActorMethod<[bigint], undefined>,
  'updateArcadeHighScore' : ActorMethod<[bigint, string, bigint], undefined>,
  'updatePipelineStatus' : ActorMethod<
    [string, PipelineStage, PipelineState],
    PipelineState
  >,
  'updateProfileProgress' : ActorMethod<
    [bigint, Array<UnitProgress>],
    undefined
  >,
  'updateSettings' : ActorMethod<[AppSettings], undefined>,
  'updateStreak' : ActorMethod<[bigint, DailyStreak], undefined>,
  'verifyParentPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];